# Generated by Django 6.0.5 on 2026-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='curso',
            field=models.CharField(default='', max_length=200, verbose_name='Curso'),
        ),
    ]
