# Generated by Django 6.0.5 on 2026-05-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_cursos_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='curso',
            field=models.CharField(default=0, max_length=200, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=500, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.cursos', verbose_name='Curso'),
        ),
    ]
