# Generated by Django 6.0.5 on 2026-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('criador_nome', models.CharField(max_length=150)),
                ('participantes_qtd', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
