# Generated by Django 6.0.4 on 2026-05-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_projeto_criador_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='criador_nome',
            new_name='criador',
        ),
    ]
