# Generated by Django 6.0.4 on 2026-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_criador_nome_projeto_criador'),
        ('profiles', '0004_alter_cursos_curso_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='curso',
        ),
        migrations.AddField(
            model_name='projeto',
            name='curso',
            field=models.ManyToManyField(related_name='projetos', to='profiles.cursos', verbose_name='Cursos do Projeto'),
        ),
    ]
