# Generated by Django 6.0.5 on 2026-05-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_sala_mensagem_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.sala'),
        ),
    ]
