# Generated by Django 6.0.5 on 2026-05-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_mensagem_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='sistema',
            field=models.BooleanField(default=False),
        ),
    ]
